### PR TITLE
Perform reloads independently of other updates

### PR DESCRIPTION
**Pull request by joelekstrom**
Fixes issue discussed in https://github.com/yapstudios/YapDatabase/issues/489

Solution is also proposed in that issue.

### CODE REVIEW

**Review by fawkeswei — COMMENTED** [review]
Should this be somehow reported to radar as well?

**Comment by joelekstrom** [comment]
Yeah, probably a good idea. Should scout openradar a bit first as well

**Review by karaiskc — APPROVED** [review]

**Review by quebin — APPROVED** [review]

**Review by Heinemark — APPROVED** [review]
Looks good, but suspect  all calls to `reloadItemsAtIndexPaths:` will be slow.

**Review by quebin — APPROVED** [review]

**Comment by joelekstrom** [comment]
@Heinemark slow in what sense? Note that for UITableView, `reloadItemsAtIndexPaths` I have removed the animation, so they should be instant in that sense. Other than that there will actually be fewer reload calls than before since they will be grouped into one

**Comment by joelekstrom** [comment]
FYI, I have also tested this code in a project that does several hundred updates per seconds, and it runs smooth on my phone!

**Pull request merged**
